# Generated by Django 3.2.14 on 2024-05-13 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TASK', '0004_auto_20220907_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='note_project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TASK.project', verbose_name='Note_project'),
        ),
    ]
